spring:
  security:
    user:
      name: admin
      password: pass
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testDev
    driverClassName: org.h2.Driver
    username: devUsername
    password: devPassword
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
  console:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:h2:mem:testQa
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
  console:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info